-- Daily AI analytics reports generated by the nightly cron.

CREATE TABLE IF NOT EXISTS public.daily_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bot_id uuid REFERENCES public.bots(id),
  report_date date NOT NULL,
  total_conversations integer DEFAULT 0,
  new_conversations integer DEFAULT 0,
  leads_captured integer DEFAULT 0,
  hot_leads integer DEFAULT 0,
  trials_activated integer DEFAULT 0,
  conversion_rate numeric(5,2),
  top_questions jsonb DEFAULT '[]'::jsonb,
  top_objections jsonb DEFAULT '[]'::jsonb,
  dropped_conversations jsonb DEFAULT '[]'::jsonb,
  actionable_insights jsonb DEFAULT '[]'::jsonb,
  featured_lead jsonb,
  comparison_yesterday jsonb,
  comparison_last_week jsonb,
  raw_ai_response text,
  telegram_sent boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  UNIQUE(bot_id, report_date)
);

CREATE INDEX IF NOT EXISTS daily_reports_bot_date_idx
  ON public.daily_reports (bot_id, report_date DESC);
